#pragma config(Sensor, S3,     sound,               sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int a=0;
int b=0;

task eventos();

task main()
{
a=-25;
nSyncedMotors=synchAB;
nSyncedTurnRatio=-100;
 while(true)
 {
  motor[motorA]=a;
  motor[motorB]=synchAB;
  wait1Msec(2000);
  if(SensorValue(sound)>40)
  {
  	a=-(a);
  }


 while(SensorValue(sound)<10)
 {
  motor[motorA]=0;
  motor[motorB]=0;
}
 }
}

task eventos()
{
  while(true)
  {
   a=SensorValue(sound);
   wait1Msec(2000);
   b=SensorValue(sound);
  }
}
